Resolve errors from type checking
tk0miya/sphinx pull request #3
Opened 2018-11-02 22:09 UTC by cocoatomo

Subject: Resolve errors from type checking

### Feature or Bugfix

- Bugfix

### Purpose
- Resolve errors from type checking
- docutils-stubs installed, Python 3.7

### Detail
- Delete unused "type: ignore" 
- Fix return type of bytes method in `path` class (str -> bytes) 
- Fix the type of the second argument of get_lvar_names function in `parser` module

### Relates
- N/A

2018-11-03 00:52 UTC, tk0miya requested changes
LGTM with nits

2018-11-03 00:52 UTC, tk0miya commented on sphinx/locale/__init__.py
>                                          languages=languages)
ここは行をつなげて、折り返さないようにするのが良さそうです。

2018-11-03 00:52 UTC, tk0miya commented on sphinx/testing/path.py
> +        # type: () -> __builtins__.bytes
なるほど、そんなテクニックが。
`import builtins` して `builtins.bytes` するものかと思ってました。

2018-11-03 00:52 UTC, tk0miya commented on sphinx/util/osutil.py
>                                       '(%r)' % fs_encoding)
(off topic)
ここ、なんで `(%r)' だけ折り返されてるんですかね…

2018-11-03 00:53 UTC, tk0miya commented
個人の repos なのでサボって日本語で書いてますw

2018-11-03 10:45 UTC, cocoatomo commented on sphinx/testing/path.py
> +        # type: () -> __builtins__.bytes
別の場所で `str` という属性を持ったクラスに出喰わしたときに発見しました。

2018-11-03 10:49 UTC, cocoatomo commented
一通りレビューに対応したのと、残りのエラーを片付けました。

2018-11-03 14:39 UTC, tk0miya commented on sphinx/roles.py
> +            msg = inliner.reporter.error('invalid PEP number %s' % target,  # type: ignore
ここ、docutils-stubs の型情報が間違っていますね
https://github.com/tk0miya/docutils-stubs/blob/9344c81e6905470ab8a8e856f1c3672a7ae80323/docutils-stubs/utils/__init__.pyi#L41-L45

`*args` は `[str, Node, Node, ...]` を期待しているので、 `Any` が望ましそうですね

2018-11-03 14:39 UTC, tk0miya commented on sphinx/roles.py
> +}  # type: Dict[str, Callable[[str, str, str, int, Inliner, Dict, List[str]], Tuple[List[nodes.Node], List[nodes.Node]]]]  # NOQA
`sphinx.util.typing:RoleFunction` を使うと読みやすいかも

2018-11-03 14:39 UTC, tk0miya commented on sphinx/util/nodes.py
> +        node['refid'] = targetid  # type:ignore
ちゃんと追いかけてないけど、ここってなんで型エラーになるんですかねえ。
`node == nodes.reference` で `reference -> TextElement -> Element` と継承関係にあるから、 `__setitem__` は持ってるはずなんだけども…

後ろでエラーになってる `node.append()` についても、 `Element` 系として認識されてないように見える。

2018-11-03 14:39 UTC, tk0miya commented on sphinx/roles.py
> +            prb = inliner.problematic(rawtext, rawtext, msg)  # type: ignore
ここって、なんてエラーが出ていたかわかります?
https://github.com/tk0miya/docutils-stubs/blob/9344c81e6905470ab8a8e856f1c3672a7ae80323/docutils-stubs/parsers/rst/states.pyi#L98

定義を見ると `problematic(str, str, system_message)` になってるから、エラーになる気がしないのだけども。

2018-11-03 15:11 UTC, cocoatomo commented on sphinx/roles.py
> +}  # type: Dict[str, Callable[[str, str, str, int, Inliner, Dict, List[str]], Tuple[List[nodes.Node], List[nodes.Node]]]]  # NOQA
そんな便利なものがあったのか

2018-11-03 15:14 UTC, tk0miya commented on sphinx/roles.py
> +}  # type: Dict[str, Callable[[str, str, str, int, Inliner, Dict, List[str]], Tuple[List[nodes.Node], List[nodes.Node]]]]  # NOQA
頻出のよく使うユーザ型を用意しておくと便利かなーと思っているのだけど、いまのところそんなに定義できてないやつですw

2018-11-03 22:38 UTC, cocoatomo commented on sphinx/util/nodes.py
> +        node['refid'] = targetid  # type:ignore
`reveal_type(node.__setitem__)` を差し込んで mypy を走らせたところ `Any` と出たので, そもそも mypy にメソッドとして認識されていないようです.
最小サンプルを作ってみましたが, そちらでは `def (Any, Any) -> Any` と出るので, `node.__setitem__` の型がうまく認識されていないようです. (型は出るので属性としての存在は認識されている.)

引き続き調べてみます.

2018-11-04 02:21 UTC, cocoatomo commented on sphinx/util/nodes.py
> +        node['refid'] = targetid  # type:ignore
私の手順が悪く、 docutils-stubs が使われていなかっただけでした。

2018-11-04 02:21 UTC, cocoatomo commented on sphinx/roles.py
> +            prb = inliner.problematic(rawtext, rawtext, msg)  # type: ignore
私の手順が悪く、 docutils-stubs が使われていなかっただけでした。

2018-11-04 11:56 UTC, cocoatomo commented
Travis CI でのチェックのしやすさを考慮して、この PR を別のアカウントに対する PR として作り直しました。
https://github.com/cocoatomo/sphinx/pull/1

2018-11-04 11:56 UTC, closed without merging